import type { Metadata } from "next";
import "./globals.css";
import { lusitana, lato } from "./ui/font";
import Navigation from "@/app/components/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lusitana.className} ${lato.className} antialiased`}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
